// Generated by Xata Codegen 0.26.5. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "papers",
    columns: [
      { name: "name", type: "text", notNull: true, defaultValue: "New paper" },
      { name: "data", type: "json", notNull: true, defaultValue: "{}" },
      { name: "user", type: "text", notNull: true, defaultValue: "" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Papers = InferredTypes["papers"];
export type PapersRecord = Papers & XataRecord;

export type DatabaseSchema = {
  papers: PapersRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL: "https://INK-ai3lvl.us-east-1.xata.sh/db/editory",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
